drop table CDDISK if exists;

drop table CDPLAYER if exists;

drop table CDTRACK if exists;

drop table CDTRACKS_LINK if exists;

create table CDDISK (
    CDDISKID bigint generated by default as identity,
    ARTIST varchar(255),
    TITLE varchar(255),
    primary key (CDDISKID)
);

create table CDPLAYER (
    CDPLAYERID bigint generated by default as identity,
    disk_CDDISKID bigint,
    primary key (CDPLAYERID)
);

create table CDTRACK (
    CDTRACKID bigint generated by default as identity,
    TITLE varchar(255),
    primary key (CDTRACKID)
);

create table CDTRACKS_LINK (
    CDDISKID bigint not null,
    CDTRACKID bigint not null
);